### PR TITLE
Add int type

### PR DESCRIPTION
**Pull request by GMSteuart**
Adds `int`, `bool`, `address`, `fixed`, `ufixed`, and `function` as acceptable types.

### CODE REVIEW

**Comment by nmushegian** [comment]
This PR is a good time to handle all basic types, there should be a list that is defined in eth ABI spec and then also a few more that are aliases in solidity

**Comment by GMSteuart** [comment]
Ill add more of them

**Comment by nmushegian** [comment]
I’m trying to find a complete list of keywords and it is surprisingly difficult, you can try reading the solidity source code to find them

**Comment by GMSteuart** [comment]
https://github.com/ethereum/solidity/blob/abaa5c0eb321aab4cd09617598696172378a4b83/liblangutil/Token.h#L209

**Comment by nmushegian** [comment]
As per chat, merging this but we need follow up issue to get the full ABI+aliases

**Pull request merged**
